### ISSUE TITLE
Add console debugger for usim

### ISSUE THREAD

**Issue by ams** [LM-3/usim#10]
Since the rewrite, we still have nice trace messages in several places, but the option handling was cleaned up and simplified.  There are two ways we can achive a nice debugging setup for usim:

- Have a debugger CLI where we can disable/enable trace messages, showing state, storing usim state, and what not during run time.  This would require running two threads, one for the simulator and one for the debugger CLI.  Drawback here is that this only allows debugging of usim, not the uhdl.

- Another way of allowing some introspection into the state of the simulator would be to make sure that the lashup setup works sensibly.  Then one can either use usim, uhdl, or a stand-alone CC program to debug either uhdl or usim.  This is the far nicest way, since it allows debugging all implementations.
 
Fixing lashup is also the simplest.  One could probobly use something like this to setup two virtual serial ports where usim and cc can communicate over:

```
socat -d -d pty,raw,echo=0 pty,raw,echo=0
```

**Comment by ams** [comment]
I was thinking of something along the lines, the interface could be similar to GDB, or similar to CC.

```
/* usim --- MIT CADR simulator
 */

#include <errno.h>
#include <pthread.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define NELEMS(a) (sizeof(a) / sizeof(a[0]))

int runningp = true;
size_t cycles = 0;
size_t max_cycles = 100;      //---!!! Set this to zero at some point.

pthread_t dbg_thread;
void *dbg_task(void *);

pthread_t sim_thread;
void *sim_task(void *);

static void
usage(void)
{
	fprintf(stderr, "usage: usim\n");
	exit(EXIT_FAILURE);
}

int
main(int argc, char **argv)
{
	int c;
	int ret;

	while ((c = getopt(argc, argv, "")) != -1) {
		switch (c) {
		case ':':
		case '?':
			usage();
		}
	}
	argc -= optind;
	argv += optind;

	ret = pthread_create(&sim_thread, NULL, sim_task, NULL);
	if (ret) {
		fprintf(stderr, "usim: pthread_create failed\n");
		exit(EXIT_FAILURE);
	}

	ret = pthread_join(sim_thread, NULL);
	if (ret) {
		fprintf(stderr, "usim: pthread_join failed\n");
		exit(EXIT_FAILURE);
	}

	ret = pthread_create(&dbg_thread, NULL, dbg_task, NULL);
	if (ret) {
		fprintf(stderr, "usim: pthread_create faileds\n");
		exit(EXIT_FAILURE);
	}

	ret = pthread_join(dbg_thread, NULL);
	if (ret) {
		fprintf(stderr, "usim: pthread_join failed\n");
		exit(EXIT_FAILURE);
	}

	exit(EXIT_SUCCESS);
}

/* Debugger
 */

/* Read a line from STDIN and return it.  */
#define DBG_RL_BUFSIZE 1024
static char *
dbg_readline(void)
{
	ssize_t bufsize = DBG_RL_BUFSIZE;
	ssize_t idx = 0;
	char *buf;

	buf = malloc(bufsize * sizeof(char));
	if (!buf) {
		fprintf(stderr, "usim: malloc of %zu bytes failed: %s\n", bufsize, strerror(errno));
		exit(EXIT_FAILURE);
	}

	while (1) {
		int c;

		c = getchar();
		if (c == EOF || c == '\n') {
			buf[idx++] = '\0';
			return buf;
		} else {
			buf[idx++] = c;
		}

		if (idx >= bufsize) {
			bufsize += DBG_RL_BUFSIZE;
			buf = realloc(buf, bufsize * sizeof(char));
			if (!buf) {
				fprintf(stderr, "usim: realloc of %zu bytes failed: %s\n", bufsize, strerror(errno));
				exit(EXIT_FAILURE);
			}
		}
	}
}

/* Split LINE into tokens (seperate by DBG_TOK_DELIM).  */
#define DBG_TOK_BUFSIZE 64
#define DBG_TOK_DELIM " \t\r\n\a"
char **
dbg_gettok(char *line)
{
	ssize_t bufsize = DBG_TOK_BUFSIZE;
	ssize_t idx = 0;
	char **tokens;

	tokens = malloc(bufsize * sizeof(char *));
	if (!tokens) {
		fprintf(stderr, "usim: malloc of %zu bytes failed: %s\n", bufsize, strerror(errno));
		exit(EXIT_FAILURE);
	}

	char *token = strtok(line, DBG_TOK_DELIM);
	while (token != NULL) {
		tokens[idx++] = token;

		if (idx >= bufsize) {
			bufsize += DBG_TOK_BUFSIZE;
			tokens = realloc(tokens, bufsize * sizeof(char *));
			if (!tokens) {
				fprintf(stderr, "usim: realloc of %zu bytes failed: %s\n", bufsize, strerror(errno));
				exit(EXIT_FAILURE);
			}
		}

		token = strtok(NULL, DBG_TOK_DELIM);
	}
	tokens[idx] = NULL;
	return tokens;
}

char *builtin_str[] = {
	"run",
	"stop",
	"info",
	"help",
	"exit"
};

/* Start simulator.  */
int
dbg_run(char **ignore)
{
	if (pthread_kill(sim_thread, 0)) {
		printf ("simulator thread not running ...\n");
		int ret;

		ret = pthread_create(&sim_thread, NULL, sim_task, NULL);
		if (ret) {
			fprintf(stderr, "usim: pthread_create failed\n");
			exit(EXIT_FAILURE);
		}

		ret = pthread_join(sim_thread, NULL);
		if (ret) {
			fprintf(stderr, "usim: pthread_join failed\n");
			exit(EXIT_FAILURE);
		}

		return 0;
	}
	runningp = true;
	return 0;
}

/* Stop simulator.  */
int
dbg_stop(char **ignore)
{
	if (pthread_kill(sim_thread, 0)) {
		printf("simulator thread not running ...\n");
		return 0;
	}
	runningp = false;
	return 0;
}

/* Show simulator state.  */
int
dbg_info(char **ignore)
{
	printf("cycles: %ld\n", cycles);
	return 0;
}

/* Show help dialog.  */
int
dbg_help(char **ignore)
{
	for (size_t i = 0; i < NELEMS(builtin_str); i++)
		printf(" %s\n", builtin_str[i]);
	return 0;
}

/* Exit usim.  */
int
dbg_exit(char **ignore)
{
	exit(EXIT_SUCCESS);
}

int(*dbg_cmds[])(char **) = {
	&dbg_run,
	&dbg_stop,
	&dbg_info,
	&dbg_help,
	&dbg_exit
};

/* Run one command from DBG_CMDS.  */
int
dbg_docmd(char **args)
{
	if (args[0] == NULL)	// Empty command.
		return 0;

	for (size_t i = 0; i < NELEMS(builtin_str); i++)
		if (strcmp(args[0], builtin_str[i]) == 0)
			return (*dbg_cmds[i])(args);

	printf("%s: no such command\n", args[0]);
	return 0;
}

/* Debugger shell.  */
void
dbg_shell(void)
{
	int ret;

	do {
		printf("usim> ");
		ret = dbg_docmd(dbg_gettok(dbg_readline()));
	} while (!ret);
}

/* Debugger thread.  */
void *
dbg_task(void *ignore)
{
	printf("debugger thread started\n");
	dbg_shell();
	printf("debugger thread done\n");
	pthread_exit(NULL);
}

/* Simulator core
 */

typedef uint64_t ucw_t;		// One MCR word.

ucw_t ir;			// Instruction register.  
size_t pc;			// Program Counter.  

/* CPU Pipeline.  */
#define p0 ir			// Current IR.
size_t p1_pc = 0;		// Current PC.
ucw_t p1 = 0;			// Next IR.
size_t p0_pc = 0;		// Next PC.

ucw_t PROM[512];
ucw_t DMEM[16*1024];

bool promenabled = true;

/* Main simulator loop.  */
void
sim_ifu(void)
{
	while (1) {
		if (!runningp) {
			sleep(1);
			continue;
		}

		/* Keep track of CPU cycles.  */
		cycles++;
		if (cycles == 0)
			cycles = 1;
		if (max_cycles && cycles > max_cycles) {
			printf("max cycle count hit (%ld)\n", cycles);
			break;
		}

		/* Fetch next instruction, and move pipeline one step
		 * forward.
		 */
		{
			p0 = p1;
			p0_pc = p1_pc;
			p1 = promenabled ? PROM[pc] : DMEM[pc];
			p1_pc = pc;
			pc++;
		}

	}
}

/* Simulator thread.  */
void *
sim_task(void *ignore)
{
	printf("simulator thread started\n");
	sim_ifu();
	printf("simulator thread done\n");
	pthread_exit(NULL);
}

/* usim ends here.  */
```

**Comment by larsbrinkhoff** [comment]
I've been using DDT a lot lately.  It's great!  It feels like Emacs, but operating on processes instead of text.

**Comment by ams** [comment]
@larsbrinkhof maybe you have a nice idea for this.

I decided to rewrite CC as more real CC/DDT, but am lost with ideas on how to handle Control-?? and Escape-?? commands. UNIX likes to catch C-c (and C-z, C-d) — easily handled by catching those.

But how would you print the input so it is semi sensible?

```
(cc) ^C        ;User inputs C-c.
```

Should one print the control character, just a ASCII representative version of it, up arrow and a `C` like in `(CC)`?

Silly problem, but sure annoys me a bit.

**Comment by larsbrinkhoff** [comment]
Well, does your terminal have the %TOSAI bit set? ;-)

ITS prints the two characters ^C, or ↑C.  And $ or ◇ for altmode.  I have gotten used to the ASCII rendition, but there's something to be said for the SAIL characters.

@lokedhs added %TOSAI handling for the Unix sudup client.

**Comment by ams** [comment]
I also like the SAIL characters, seems much more logical.  

Though I think I just decided to keep things utterly simple, no Control/Escape handling -- user inputs literal `^` and `C` for `C-c`.  It doesn't have to be exactly like `(CC)` or DDT (it will never be that, since what I normally use is the real `(CC)` anyway!). Since this is mostly VT100 terminals that is easier, and simple to do.

**Comment by larsbrinkhoff** [comment]
WAT NO

The beauty of DDT is that the keyboard commands are much like Emacs.  It's very interactive.  Control-Meta-X to kill a job.  Meta-B to set a breakpoint.  Control-F to list files.

**Comment by ams** [comment]
Yeah, but if you want real debugging of the MIT CADR you should be using another MIT CADR or ITS. ! Then you get proper input handling and SAIL characters.    This is already doable, just needs some hand holding.

The CC version written in C is just a crude hack when debugging some parts of the FPGA rig when you don't want to spin up the simulator or another card, and a bit easier to debug.

**Comment by larsbrinkhoff** [comment]
Now I'm curious, how to you debug a CADR from ITS?

**Comment by ams** [comment]
All you do is hook up the debugger (ITS, or another CADR) to your debuggee (CADR) on the UNIBUS using a flat cable between the two.  Then on the debugger you can load and call `(CC)` in MACLISP and now you can step, set break points, print Qs, and memory on the debugger.

Of course, you need a real machine running ITS.  Unless you hack SIMH to map the required addresses on the UNIBUS to talk to a serial port which is connected to a CADR FPGA (which I do for CADR<->CADR debugging).

**Comment by ams** [comment]
Added a (CC) like program in 487969d59222066f80a6ffb4dabece744ee75ce5.  Still needs work, but it is a start.

**Comment by ams** [comment]
The 'cc' command will be removed shortly.

**Comment by ams** [comment]
It has now been removed.  Use CC for debugging (still needs to be implemented)
