### ISSUE TITLE
Bands not where they are expected

### ISSUE THREAD

**Issue by ams** [LM-3/usim#49]
In #47 it was noted that"

> sidenote: the documentation says that bands is expected beneath the usim directory. It isn't. It actually has to be alongside it for anything to work. Not really a big deal...),

`diskmaker.c` points out ../bands and not ./bands, so not sure why it was looking for them alongside?

Or is this a confusion in terminology, i.e. that usim and bands should be in the same level, but `diskmaker` expects them to be under.

Guess the wording could need clearing up...

**Comment by ThothXV** [comment]
Yeah, since I'm the one who originally wrote that I should probably explain what I meant...

It seems like the docs implies that the tree should look like this

```
-+  /
 +-+  /usim
 | |  /usim/bands
 | |  /usim/diskmaker
```

When the actual expected layout is

```
-+  /
 +-+  /usim
 | |  /usim/diskmaker
 |  /bands
```
My apologies for the crudeness of my ASCII art.
```

**Comment by ams** [comment]
See also #13 .

**Comment by ams** [comment]
I've resolved this by virtue of submodules.  Obviously, still need to fix the documentation.   But I'm closing this for now, since documentation has another issue #6 .
